language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test-prettier
  - travis_wait 30 npm run test-ci && cat ./coverage/lcov.info | npx coveralls
  - npm run build
